name: 'Build and Test'

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy artifacts
        shell: bash
        run: |
          mkdir dist
          cp build/libs/*.jar dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: dist/*